/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clave_valor.h"
#include <pthread.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <strings.h>
#include <sys/types.h>

#define MAX_TUPLAS 100
#define MAX_C	256

typedef struct{
    int clave;
    char valor1[MAX_C];
    int N;
    double *vector;
}Tupla;

pthread_mutex_t mutex_tuplas = PTHREAD_MUTEX_INITIALIZER;
pthread_mutex_t mutex_keys = PTHREAD_MUTEX_INITIALIZER;
pthread_mutex_t mutex_archivo = PTHREAD_MUTEX_INITIALIZER;

Tupla tuplas[MAX_TUPLAS];
int keys[MAX_TUPLAS]; // Array para almacenar las claves
int numTuplas = 0;    // Variable global para almacenar el número actual de tuplas

// Definición de la variable global para el nombre del archivo
char filename[FILENAME_MAX];

// Función para escribir las tuplas en un archivo de texto
void escribirTuplas()
{
    pthread_mutex_lock(&mutex_archivo);
    FILE *fp = fopen(filename, "w");
    if (fp == NULL)
    {
        printf("Error al abrir el archivo para escribir.\n");
        pthread_mutex_unlock(&mutex_archivo);
        return;
    }

    for (int i = 0; i < numTuplas; i++)
    {
        fprintf(fp, "%d,%s", tuplas[i].clave, tuplas[i].valor1);
        for (int j = 0; j < tuplas[i].N; j++)
        {
            fprintf(fp, ",%.2f", tuplas[i].vector[j]);
        }
        fprintf(fp, "\n");
    }

    fclose(fp);
    pthread_mutex_unlock(&mutex_archivo);
}

// Función para leer las tuplas desde un archivo de texto
void leerTuplas()
{
    pthread_mutex_lock(&mutex_archivo);
    FILE *fp = fopen(filename, "r");
    if (fp == NULL)
    {
        printf("Error al abrir el archivo para leer.\n");
        pthread_mutex_unlock(&mutex_archivo);
        return;
    }

    while (!feof(fp) && numTuplas < MAX_TUPLAS)
    {
        Tupla t;
        int result = fscanf(fp, "%d,%[^,],%d", &t.clave, t.valor1, &t.N);
        if (result == EOF)
        {
            break;
        }
        t.vector = (double *)malloc(t.N * sizeof(double));
        for (int i = 0; i < t.N; i++)
        {
            fscanf(fp, ",%lf", &t.vector[i]);
        }
        pthread_mutex_lock(&mutex_tuplas);
        pthread_mutex_lock(&mutex_keys);
        tuplas[numTuplas] = t;
        keys[numTuplas] = t.clave;
        numTuplas++;
        pthread_mutex_unlock(&mutex_keys);
        pthread_mutex_unlock(&mutex_tuplas);
    }

    fclose(fp);
    pthread_mutex_unlock(&mutex_archivo);
}

bool_t
init_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	printf("Inicializado\n");

    strcpy(filename, "datos");
    remove(filename);
    escribirTuplas();
    leerTuplas();

    *result = 0;

	return retval;
}


bool_t
set_value_1_svc(value_args arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	printf("Seteado valor\n");
	Tupla t;
	t.clave = arg1.key;
	strcpy(t.valor1, arg1.value1);
	t.N = arg1.N_value2;
	t.vector = (double *)malloc(arg1.N_value2 * sizeof(double));
	for (int i = 0; i < arg1.N_value2; i++) {
		t.vector[i] = arg1.V_value2.double_array_val[i]; // Accede a los elementos del array con .V_value2_val
	}

	pthread_mutex_lock(&mutex_tuplas);
	pthread_mutex_lock(&mutex_keys);
	for (int i = 0; i < numTuplas; i++) {
		if (keys[i] == arg1.key) {
			pthread_mutex_unlock(&mutex_keys);
			pthread_mutex_unlock(&mutex_tuplas);
			*result = -1;
			return retval;
		}
	}

	tuplas[numTuplas] = t;
	keys[numTuplas] = arg1.key;
	numTuplas++;
	pthread_mutex_unlock(&mutex_keys);
	pthread_mutex_unlock(&mutex_tuplas);

	escribirTuplas();

	*result = 0;
	return retval;
}


bool_t get_value_1_svc(int key, get_value_result *result,  struct svc_req *rqstp) {
    bool_t retval = TRUE;

    printf("Obteniendo valor\n");

    pthread_mutex_lock(&mutex_tuplas);
    pthread_mutex_lock(&mutex_keys);

    for (int i = 0; i < numTuplas; i++) {
        if (keys[i] == key) {
            result->status = 0;
            result->value1 = (char *)malloc(MAX_C * sizeof(char));
            result->N_value2 = tuplas[i].N;

            // Comprueba si la asignación de memoria fue exitosa
            if (result->value1 == NULL) {
                printf("Error: no se pudo asignar memoria para value1\n");
                return FALSE;
            }

            strcpy(result->value1, tuplas[i].valor1);

            result->V_value2.double_array_len = tuplas[i].N;
            result->V_value2.double_array_val = (double *)malloc(result->N_value2 * sizeof(double));

            // Comprueba si la asignación de memoria fue exitosa
            if (result->V_value2.double_array_val == NULL) {
                printf("Error: no se pudo asignar memoria para V_value2.double_array_val\n");
                return FALSE;
            }

            for (int j = 0; j < result->N_value2; j++) {
                result->V_value2.double_array_val[j] = tuplas[i].vector[j];
            }

            pthread_mutex_unlock(&mutex_keys);
            pthread_mutex_unlock(&mutex_tuplas);
            return retval;
        }
    }

    pthread_mutex_unlock(&mutex_keys);
    pthread_mutex_unlock(&mutex_tuplas);

    result->status = -1;
    return retval;
}



bool_t
modify_value_1_svc(value_args arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	printf("Modificando valor\n");

	pthread_mutex_lock(&mutex_tuplas);
	pthread_mutex_lock(&mutex_keys);

	for (int i = 0; i < numTuplas; i++)
	{
		if (keys[i] == arg1.key)
		{
			strcpy(tuplas[i].valor1, arg1.value1);
			tuplas[i].N = arg1.N_value2;

			if (tuplas[i].vector != NULL)
			{
				free(tuplas[i].vector);  // Libera la memoria previamente asignada si existe
			}
			
			tuplas[i].vector = (double *)malloc(arg1.N_value2 * sizeof(double));
			
			for (int j = 0; j < arg1.N_value2; j++)
			{
				tuplas[i].vector[j] = arg1.V_value2.double_array_val[j];
			}

			pthread_mutex_unlock(&mutex_keys);
			pthread_mutex_unlock(&mutex_tuplas);
			escribirTuplas();
			*result = 0;
			return retval;
		}
	}

	pthread_mutex_unlock(&mutex_keys);
	pthread_mutex_unlock(&mutex_tuplas);
	*result = -1;
	return retval;
}


bool_t
delete_key_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	printf("Borrando clave\n");
	pthread_mutex_lock(&mutex_tuplas);
	pthread_mutex_lock(&mutex_keys);
	for (int i = 0; i < numTuplas; i++)
	{
		if (keys[i] == key)
		{
			for (int j = i; j < numTuplas - 1; j++)
			{
				tuplas[j] = tuplas[j + 1];
				keys[j] = keys[j + 1];
			}
			numTuplas--;
			pthread_mutex_unlock(&mutex_keys);
			pthread_mutex_unlock(&mutex_tuplas);
			escribirTuplas();
			*result = 0;
			return retval;
		}
	}
	pthread_mutex_unlock(&mutex_keys);
	pthread_mutex_unlock(&mutex_tuplas);
	*result = -1;
	return retval;
}


bool_t
exist_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	printf("Comprobando existencia\n");
	pthread_mutex_lock(&mutex_keys);
	for (int i = 0; i < numTuplas; i++)
	{
		if (keys[i] == key)
		{
			pthread_mutex_unlock(&mutex_keys);
			*result = 1;
			return retval;
		}
	}
	pthread_mutex_unlock(&mutex_keys);
	*result = 0;
	return retval;
}


int
clave_valor_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
