/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clave_valor.h"

bool_t
xdr_double_array (XDR *xdrs, double_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->double_array_val, (u_int *) &objp->double_array_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_value_args (XDR *xdrs, value_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_double_array (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_value_result (XDR *xdrs, get_value_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_double_array (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}
